<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="AnalayzeBatch" Id="{41693958-d985-4cab-8020-bde87749fe76}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION AnalayzeBatch : ST_ProductStats
VAR_INPUT
	aProdArray : REFERENCE TO ARRAY[1..20] OF REAL ;
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
AnalayzeBatch.fAverageWeight := CalculateAverage(aProdArray);
FindMinMax(aProdArray, nMinWeight => AnalayzeBatch.fminWeight, nMaxWeight => AnalayzeBatch.fmaxWeight);
AnalayzeBatch.nDefectiveCount := CountDefects(aProdArray);

]]></ST>
    </Implementation>
    <LineIds Name="AnalayzeBatch">
      <LineId Id="26" Count="0" />
      <LineId Id="22" Count="3" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>