<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{864c6c48-a6ed-4662-b6a7-4e5a364ffb3e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
aProductArray : ARRAY[1..20] OF REAL := [23,120,35,100,250,300,500,230,190,30,10,600,240,210,10000,8600,11,349.444,42.252,534.2];
stProductAnalysis : ST_ProductStats;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[stProductAnalysis := AnalayzeBatch(aProductArray);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>